config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root "users/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }

  resources :messages do
    collection {post :import}
    collection {post :line_receive}
  end

end

app/views/layouts/_header.html.erb
<header class="navbar p-0 navbar-fixed-top navbar-inverse">
      <ul class="nav mr-auto">
        <li class="nav-link logo">
          <a>メールボム</a>
        </li>
      </ul>
      <ul class="nav">
        <li class="nav-link"><%= link_to "アカウント設定", edit_user_registration_path %></li>
        <li class="nav-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      </ul>
</header>

app/views/layouts/_sidebar.html.erb
<div class="listings">
  <div class="listings_channels">
    <ul class="channel_list text-center">
      <%= sidebar_link_item('送信メッセージ一覧', messages_path) %>
      <%= sidebar_link_item('送信フォーム', new_message_path) %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% unless page_title.include?("ログイン") %>
      <%= render 'layouts/header' %>
    <% end %>

    <% flash.each do |key, value| %>
      <p class="alert alert-<%= key %>">
        <%= value %>
      </p>
    <% end %>
  </head>

  <body>
    <div class="row">
      <% unless page_title.include?("ログイン") %>
        <div class="col-md-2">
          <%= render'layouts/sidebar' %>
        </div>
      <% end %>
      <div class="col-md-10 mx-auto mt-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>